name: partner_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  page_transition: ^2.0.9
  google_sign_in: ^6.1.2
  firebase_auth: ^4.6.1
  http: ^1.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  shared_preferences: ^2.1.2
  badges: ^3.1.1
  provider: ^6.0.5
  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^14.1.1
  firebase_in_app_messaging: ^0.7.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/products/
